### ISSUE TITLE
v1.10.5 causes crashing.

### ISSUE THREAD

**Issue by Random-Stack-Random-Day** [phroph/magicsim#6]
Unsure on Event log locations to provide anything, but since v1.10.5 of SimC, MagicSim will crash on 'Generating Profile'. 

Let me know what to provide info wise, but this was reproducible on several setups.

**Comment by phroph** [comment]
Fixed in the most recent PR. This will be updated when I get back to my home computer (thats the only way I generate the required data to upload a new release).

**Comment by Random-Stack-Random-Day** [comment]
Still seeing this issue pretty frequently on both my PC and my wifes. 1 out of every ~5 sims. Is there a log I can provide?
